### ISSUE TITLE
Error installing avr-gcc

### ISSUE THREAD

**Issue by trombonehero** [jpommerening/homebrew-avr#3]
Hi,

Thanks for packaging up these AVR tools! I'm attempting to install `simulavr`, but Homebrew gets stuck on `avr-gcc`:

```
==> Installing simulavr from jpommerening/homebrew-avr
==> Installing dependencies for simulavr: avr-gcc, avr-libc, swig-13
==> Installing simulavr dependency: avr-gcc
==> Downloading http://ftp.gnu.org/gnu/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/avr-gcc-4.9.2.tar.bz2
Error: undefined method `nocxx?' for #<Formulary::Formulae::AvrGcc:0x007f9ce412a
0b0>
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/jpommerening/homebrew-avr/avr-gcc.rb:62:in `install'
/usr/local/Library/Homebrew/build.rb:136:in `block in install'
/usr/local/Library/Homebrew/formula.rb:402:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:757:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:755:in `stage'
/usr/local/Library/Homebrew/formula.rb:398:in `brew'
/usr/local/Library/Homebrew/build.rb:114:in `install'
/usr/local/Library/Homebrew/build.rb:185:in `<main>'
```

I'm running Yosemite and an up-to-date Homebrew.

**Comment by jpommerening** [comment]
Hmm I think I see what's going on there. I wonder how it didn't break when I was using it.

Anyway, could you do a `brew update` and try again?

**Comment by jpommerening** [comment]
Hey @trombonehero, just in case you missed my previous comment: Can you give it another shot and let me know if it works?

**Comment by trombonehero** [comment]
Hi @jpommerening, sorry for my delay in replying. As a short-term measure (I'm currently working to a deadline) I cobbled together a Frankenstein's monster of your formulae, @larsimmisch's formulae and a lot of `brew install --overwrite`. It's not pretty, but it seems to work. In a couple of days I will have a chance to step back and do it "the right way", namely, try to make the issue reproducible.

**Comment by jpommerening** [comment]
Haha, good to hear you figured something out. Good luck with that deadline!
